### ISSUE TITLE
Ghosttext does not behave as expected on Codepen

### ISSUE THREAD

**Issue by Azeirah** [GhostText/GhostText#45] opened 2015-02-14 15:44 UTC
I can pick an editor on Codepen using the browser plugin, but the editor I select doesn't get highlighted, and typing in Sublime doesn't affect the editor.

It's a problem specifically on Codepen.io, it's not a codemirror issue, since ghosttext works fine on JSFiddle.

Note that I've only tried this in Firefox, I had some issues with my chrome browser, rendering me unable to install ghosttext.

**Comment by Cacodaimon** [comment] 2015-02-14 19:11
I can't reproduce this behavior on Linux with Firefox 35.0.1, which system and version are you using?

**Comment by Azeirah** [comment] 2015-02-14 19:44
I'm using Windows 7 with Firefox developer edition @ 37.0a2

**Comment by Cacodaimon** [comment] 2015-02-18 12:44
I can reproduce this on Windows 7 with the latest developer edition.

It is really strange whats happening here, using GhostText with Firefox 35 works fine with codepen.io and the developer edition works on other pages using a codemirror, too.

I need some more time investigating what is happening here.

**Comment by bfred-it** [comment] 2016-09-06 13:25
Closing this as the old Firefox extension has been replaced.

Can you test the new version using the [installation instructions in the readme](https://github.com/GhostText/GhostText/blob/master/browser/README.md#on-firefox)?

**Closed by bfred-it** 2016-09-06 13:25 UTC
Labels: firefox, sublime-text
