### ISSUE TITLE
Multiple text editors are opened in Sublimetext when editing Gmail letter

### ISSUE THREAD

**Issue by angordeyev** [GhostText/GhostText#163] opened 2019-10-31 08:53 UTC
Environment:
Sublimetext 3.2.2 build 3211
Chrome 77.0.3865.90 (Official Build) (64-bit)
GhostText 17.12.11.910
[
![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/gUOqPlcOjHY/0.jpg)](https://www.youtube.com/watch?v=gUOqPlcOjHY)

**Comment by fregante** [comment] 2019-10-31 09:09
Thank you for the report. This happens when clicking the GhostText button multiple times on the same page.

**Comment by fregante** [comment] 2019-10-31 09:09
Duplicate of https://github.com/GhostText/GhostText/issues/114

**Closed by fregante** 2019-10-31 09:09 UTC
